site_name: Dev Solutions
site_description: Documentation for Dev Solutions projects
site_author: Yan Naing Htwe
site_url: https://orandian.github.io/dev-solutions/

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.expand      # Expand nested nav automatically
    - content.code.copy      # Copy button for code blocks
    - search.highlight       # Highlight search results
    - search.suggest         # Suggest search results as typing
    - header.autohide        # Hide header when scrolling 

nav:
  - Home: index.md
  - Nest:
      - Server Setup: nest/server_setup.md
  - Git:
      - Merge Conflict: git/merge-conflict.md
      - Detached Head: git/detached-head.md
      - Branching & Merging: git/branching-merging.md
      - Industry Git Commands: git/industry_git_commands.md
  - Hosting:
      - Vercel Deploy: hosting/vercel-deploy.md
  - Caddy:
      - SSL Renewal: caddy/ssl-renewal.md
  - CI/CD:
      - Spring Boot CI/CD Setup Guide: CI_CD/spring_boot_ci_cd_setup_guide.md
  - Docker:
      - Spring boot process: docker/docker_process_guide.md
      - Essential Docker Commands: docker/essential_docker_commands.md
  - AWS:
      - SQS Guide: aws/aws-sqs-guide.md
      - SNS Guide: aws/aws-sns-guide.md
      - Kinesis Data Streams: aws/aws-kinesis-data-streams.md
      - SQS vs SNS vs Kinesis: aws/sqs-vs-sns-vs-kinesis.md
      - Amazon Managed Service for Apache Flink: aws/aws-apache-flink.md
      - Amazon Data Firehose: aws/aws-data-firehose.md
      - AWS AI Practitioner: aws/aws-ai-practitioner.md
  - Kubernetes:
      - Kubernetes Comprehensive Guide: kubernetes/kubernetes_comprehensive_guide.md
  - Expo:
      - Expo Solutions Guide: expo/expo_solutions_guide.md
  - React:
      - State Management: react/state_management.md
      
